#!/usr/bin/env python3
"""Detect installed agent CLIs and coarse auth health (no secrets).

Usage:
  python tools/session/detect_agents.py
  python tools/session/detect_agents.py --root /path/to/project --write

Writes markdown table to stdout. With --write, updates/creates the
Agent CLIs section in .agents/PRJ_REFERENCE.md (or docs copy when developing
the kit). Never prints tokens or env secret values.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# id → (binaries to try, optional auth probe argv — exit 0 ≈ logged in)
AGENTS: list[tuple[str, tuple[str, ...], tuple[str, ...] | None]] = [
    ("claude", ("claude",), ("claude", "auth", "status")),
    ("codex", ("codex",), None),
    ("opencode", ("opencode",), None),
    ("cursor", ("cursor", "cursor-agent"), None),
    ("antigravity", ("antigravity",), None),
    ("gemini", ("gemini",), None),
    ("aider", ("aider",), None),
]


def find_root(start: Path) -> Path:
    cur = start.resolve()
    for candidate in [cur, *cur.parents]:
        if (candidate / ".agents").is_dir() or (candidate / ".agent-work").is_dir():
            return candidate
        if (candidate / "docs" / "artifact-schemas.json").is_file():
            return candidate
    return start.resolve()


def probe_auth(argv: tuple[str, ...] | None) -> str:
    """Return auth_ok | auth_unknown | auth_fail. Never echo command output (may leak)."""
    if not argv:
        return "auth_unknown"
    try:
        proc = subprocess.run(
            list(argv),
            capture_output=True,
            text=True,
            timeout=8,
            check=False,
        )
        if proc.returncode == 0:
            return "auth_ok"
        return "auth_fail"
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return "auth_unknown"


def detect() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for agent_id, binaries, auth_cmd in AGENTS:
        path = None
        for b in binaries:
            path = shutil.which(b)
            if path:
                break
        if not path:
            rows.append(
                {
                    "id": agent_id,
                    "status": "missing",
                    "path": "",
                    "auth": "n/a",
                    "notes": "binary not on PATH",
                }
            )
            continue
        auth = probe_auth(auth_cmd)
        status = "available" if auth in ("auth_ok", "auth_unknown") else "auth_unknown"
        if auth == "auth_fail":
            status = "auth_unknown"
        rows.append(
            {
                "id": agent_id,
                "status": status,
                "path": path,
                "auth": auth,
                "notes": "do not treat auth_unknown as proof of login",
            }
        )
    return rows


def render_table(rows: list[dict[str, str]]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "## Agent CLIs",
        "",
        f"<!-- Generated by detect_agents.py at {now}. No secrets. -->",
        "",
        "| CLI id | Status | Path | Auth probe | Notes |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['id']}` | {r['status']} | `{r['path'] or '—'}` | {r['auth']} | {r['notes']} |"
        )
    lines.extend(
        [
            "",
            "Status: `available` (on PATH) · `auth_unknown` (present but login unclear) · "
            "`missing`. Prefer `rules.agents.routing` + fallback `main` when unsure.",
            "",
        ]
    )
    return "\n".join(lines)


SECTION_RE = re.compile(
    r"^## Agent CLIs\s*$.*?(?=^## |\Z)",
    re.M | re.S,
)


def write_prj_reference(root: Path, section: str) -> Path:
    target = root / ".agents" / "PRJ_REFERENCE.md"
    if not (root / ".agents").is_dir():
        raise SystemExit(
            "No .agents/ — run init / install first before detect_agents --write"
        )
    if not target.is_file():
        tmpl = None
        for cand in (
            root / ".agents" / "skills" / "init" / "templates" / "PRJ_REFERENCE.template.md",
            root / "skills" / "init" / "templates" / "PRJ_REFERENCE.template.md",
            Path(__file__).resolve().parents[2]
            / "skills"
            / "init"
            / "templates"
            / "PRJ_REFERENCE.template.md",
        ):
            if cand.is_file():
                tmpl = cand
                break
        if tmpl is not None:
            target.write_text(tmpl.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            target.write_text(
                "# Project Reference\n\n## Freshness\n\n- Mode: detect_agents\n",
                encoding="utf-8",
            )

    text = target.read_text(encoding="utf-8")
    if SECTION_RE.search(text):
        text = SECTION_RE.sub(section.rstrip() + "\n\n", text)
    else:
        if re.search(r"^## Freshness\s*$", text, re.M):
            text = re.sub(
                r"^## Freshness\s*$",
                section.rstrip() + "\n\n## Freshness",
                text,
                count=1,
                flags=re.M,
            )
        else:
            text = text.rstrip() + "\n\n" + section
    target.write_text(text if text.endswith("\n") else text + "\n", encoding="utf-8")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Upsert ## Agent CLIs into .agents/PRJ_REFERENCE.md",
    )
    args = parser.parse_args()
    root = args.root.resolve() if args.root else find_root(Path.cwd())
    rows = detect()
    section = render_table(rows)
    print(section)
    if args.write:
        path = write_prj_reference(root, section)
        print(f"DETECT_AGENTS_OK path={path}", file=sys.stderr)
    available = sum(1 for r in rows if r["status"] != "missing")
    print(f"DETECT_AGENTS_SUMMARY available_or_unknown={available} total={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
