#!/usr/bin/env python3
"""tools/providers/compile.py — compile skills for a target provider.

Port of aix `@x/providers` adapters (claude/cursor/codex/gemini), dependency-free.
Reads skill dirs under `skills/`, extracts frontmatter + body, and emits the
provider-specific file set into a target directory (default `.agents`).

Usage:
  python tools/providers/compile.py --provider claude --skills-root skills --target out
  python tools/providers/compile.py --provider all --skills-root skills --target out
  python tools/providers/compile.py --list-providers
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

PROVIDERS = ("claude", "cursor", "codex", "gemini")
FRONTMATTER_HEADER = "---\n# generated by aix\n"
HEADER = "# generated by aix\n\n"


@dataclass
class SkillDoc:
    id: str
    name: str
    description: str
    kind: str
    version: str
    tags: list[str]
    roles: list[str]
    compatible: list[str]
    body: str


@dataclass
class EmittedFile:
    path: str
    contents: str


def _fm_value(fm: str, key: str) -> str:
    m = re.search(rf"^{key}:[ \t]*(.*)$", fm, re.MULTILINE)
    if not m:
        return ""
    first = m.group(1).strip()
    if first:
        return first
    items: list[str] = []
    for line in fm[m.end() :].splitlines():
        if not line.strip():
            continue
        if re.match(r"^\s+-\s+", line):
            items.append(line.strip()[2:].strip())
        else:
            break
    return "[" + ", ".join(items) + "]"


def _list_value(fm: str, key: str, default: list[str] | None = None) -> list[str]:
    raw = _fm_value(fm, key)
    if not raw:
        return list(default or [])
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        raw = raw[1:-1]
    return [v.strip().strip("'\"") for v in raw.split(",") if v.strip()]


def _scalar(fm: str, key: str, default: str = "") -> str:
    """Read a scalar value, resolving YAML block scalars (`>+`, `|-`, `>`).

    Handles:
      description: plain text
      description: "quoted text"
      description: >+
        indented block
    """
    m = re.search(rf"^{key}:[ \t]*(.*)$", fm, re.MULTILINE)
    if not m:
        return default
    first = m.group(1).strip()
    if not first.startswith((">", "|")):
        return first.strip().strip("'\"")
    # Block scalar: collect following indented lines until dedent.
    lines: list[str] = []
    for line in fm[m.end() :].splitlines():
        if not line.strip():
            lines.append("")
            continue
        if re.match(r"^\s{2,}", line):
            lines.append(line.lstrip())
        else:
            break
    # Strip trailing blank lines from a folded/literal block.
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines).strip()


def load_skills(skills_root: Path) -> list[SkillDoc]:
    docs: list[SkillDoc] = []
    for skill_dir in sorted(skills_root.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        text = skill_md.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            continue
        end = text.find("\n---", 4)
        if end < 0:
            continue
        fm = text[4:end]
        body = text[end + 4 :].lstrip("\n")
        name = _scalar(fm, "name", skill_dir.name)
        docs.append(
            SkillDoc(
                id=skill_dir.name,
                name=name,
                description=_scalar(fm, "description"),
                kind=_scalar(fm, "x-kind", "domain"),
                version=_scalar(fm, "x-version", "0.1.0"),
                tags=_list_value(fm, "x-tags"),
                roles=_list_value(fm, "x-roles"),
                compatible=_list_value(fm, "x-compatible", list(PROVIDERS)),
                body=body,
            )
        )
    return docs


def _yaml_string(value: str) -> str:
    return json.dumps(value)


def _yaml_array(values: list[str]) -> str:
    return "[" + ", ".join(_yaml_string(v) for v in values) + "]"


def render_skill_file(skill: SkillDoc) -> str:
    return (
        f"{FRONTMATTER_HEADER}name: {_yaml_string(skill.name)}\n"
        f"description: {_yaml_string(skill.description)}\n"
        f"x-kind: {_yaml_string(skill.kind)}\n"
        f"x-version: {_yaml_string(skill.version)}\n"
        f"x-tags: {_yaml_array(skill.tags)}\n"
        f"x-roles: {_yaml_array(skill.roles)}\n"
        f"x-compatible: {_yaml_array(skill.compatible)}\n"
        f"---\n\n{skill.body}"
    )


def emit_claude(skills: list[SkillDoc]) -> list[EmittedFile]:
    files: list[EmittedFile] = []
    for skill in skills:
        files.append(
            EmittedFile(
                f"content/skills/{skill.id}/SKILL.md",
                render_skill_file(skill),
            )
        )
    files.append(
        EmittedFile(
            ".claude-plugin/plugin.json",
            json.dumps(
                {
                    "name": "simple-skills",
                    "version": "0.1.0",
                    "description": "Simple Skills agent kit",
                    "author": {"name": "truongnat"},
                    "skills": ["./content/skills/"],
                },
                indent=2,
            ),
        )
    )
    return files


def emit_cursor(skills: list[SkillDoc]) -> list[EmittedFile]:
    files: list[EmittedFile] = []
    for skill in skills:
        files.append(
            EmittedFile(
                f".cursor/rules/aix-skill-{skill.id}.mdc",
                f"{FRONTMATTER_HEADER}description: {_yaml_string(skill.description)}\n"
                f'globs: "*"\nalwaysApply: false\n---\n\n# {skill.name}\n\n{skill.body}',
            )
        )
    return files


def emit_codex(skills: list[SkillDoc]) -> list[EmittedFile]:
    files: list[EmittedFile] = []
    for skill in skills:
        files.append(
            EmittedFile(
                f".codex/skills/{skill.id}/SKILL.md",
                render_skill_file(skill),
            )
        )
    return files


def emit_gemini(skills: list[SkillDoc]) -> list[EmittedFile]:
    files: list[EmittedFile] = []
    for skill in skills:
        files.append(
            EmittedFile(
                f".agents/skills/{skill.id}/SKILL.md",
                render_skill_file(skill),
            )
        )
    files.append(
        EmittedFile(
            "gemini-extension.json",
            json.dumps(
                {
                    "name": "simple-skills",
                    "version": "0.1.0",
                    "description": "Simple Skills agent kit",
                    "skills": [s.id for s in skills],
                },
                indent=2,
            ),
        )
    )
    return files


EMITTERS = {
    "claude": emit_claude,
    "cursor": emit_cursor,
    "codex": emit_codex,
    "gemini": emit_gemini,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--provider", default="all", help=f"one of {PROVIDERS} or 'all'")
    parser.add_argument("--skills-root", type=Path, required=True)
    parser.add_argument("--target", type=Path, required=True)
    parser.add_argument("--list-providers", action="store_true")
    args = parser.parse_args()

    if args.list_providers:
        print("\n".join(PROVIDERS))
        return 0

    skills = load_skills(args.skills_root)
    if not skills:
        print(f"ERROR: no skills found under {args.skills_root}", file=sys.stderr)
        return 2

    providers = PROVIDERS if args.provider == "all" else [args.provider]
    if args.provider not in PROVIDERS and args.provider != "all":
        print(f"ERROR: unknown provider {args.provider!r}; use one of {PROVIDERS} or 'all'", file=sys.stderr)
        return 2

    total = 0
    for provider in providers:
        files = EMITTERS[provider](skills)
        for f in files:
            dest = args.target / f.path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(f.contents, encoding="utf-8")
        total += len(files)
        print(f"[{provider}] emitted {len(files)} files for {len(skills)} skills")

    print(f"done: {total} files → {args.target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
