from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

P1 = {
    'sk-accounting-pro': ('references/accounting-validation-matrix.md', 'Accounting validation matrix', [
        ('Double-entry balance', 'Post a 1,250 expense with cash credit; debit and credit totals both equal 1,250.', 'Journal export, trial-balance totals, reviewer initials.', 'Unposted subledger or rounding mismatch blocks close.', 'sk-tester -> sk-verify-pro'),
        ('Period close', 'Lock March only after accruals, cut-off and retained earnings roll-forward reconcile.', 'Close checklist, period-lock audit event, trial balance before/after.', 'Late March invoice remains in April queue and is disclosed.', 'sk-review -> sk-verify-pro'),
        ('Reversal', 'Reverse an accrual in April with a linked original entry; never edit the posted March entry.', 'Original/reversal IDs, equal-and-opposite lines, timestamps.', 'Unlinked reversal blocks audit-trail acceptance.', 'sk-accounting-pro -> sk-review'),
        ('FX', 'Revalue a EUR payable at the approved close rate and post realized/unrealized FX separately.', 'Rate source/date, calculation sheet, journal IDs.', 'Missing rate provenance or mixed currencies blocks posting.', 'sk-review -> sk-verify-pro'),
        ('Reconciliation', 'Bank balance plus timing items equals the adjusted book balance; unexplained difference stays open.', 'Reconciliation statement, unmatched-item register, owner/date.', 'Do not force-balance with a suspense entry without approval.', 'sk-accounting-pro -> sk-planning'),
        ('Audit trail', 'Every adjustment retains actor, reason, source document and approval chain.', 'Immutable event log and source-document links with redacted fixture IDs.', 'PII or secrets are never copied into fixtures.', 'sk-accounting-pro -> sk-review'),
        ('Known-answer statement', 'A fixture trial balance produces assets = liabilities + equity and net income matches the control total.', 'Known-answer totals and comparison output.', 'Different accounting basis is a limitation, not a pass.', 'sk-verify-pro'),
        ('Failure/recovery', 'If posting fails after validation, retry idempotently or quarantine the batch; do not duplicate entries.', 'Failure log, retry key, quarantine/replay result.', 'Named owner must approve replay and period impact.', 'sk-tester -> sk-verify-pro'),
    ]),
    'sk-expo-data-fetching': ('references/data-fetching-validation-matrix.md', 'Expo data-fetching state and verification matrix', [
        ('HTTP error', 'A 500 response renders a retryable error state and preserves safe request context.', 'Test log, rendered state assertion, redacted request ID.', 'No silent fallback to stale data.', 'sk-tester -> sk-verify-pro'),
        ('Malformed payload', 'Schema parsing rejects missing required fields and exposes a typed UI error.', 'Fixture payload, parser result, UI assertion.', 'Never persist unvalidated payloads.', 'sk-review -> sk-verify-pro'),
        ('Timeout', 'A bounded timeout cancels the request and offers retry without duplicate mutation.', 'Fake-timer result, cancellation signal, retry count.', 'Unbounded waits block release.', 'sk-tester -> sk-verify-pro'),
        ('Offline queue', 'A safe mutation queues offline, shows pending status, and replays once after reconnect.', 'Queue snapshot, replay key, network transition log.', 'Conflict policy must be explicit before replay.', 'sk-expo-data-fetching -> sk-review'),
        ('Cancellation', 'Leaving the screen aborts the request and prevents state updates on an unmounted owner.', 'Abort signal assertion and no-update-after-unmount test.', 'Do not treat cancellation as a user-visible failure.', 'sk-tester -> sk-verify-pro'),
        ('Token refresh concurrency', 'Concurrent 401s share one refresh promise; only the original requests retry once.', 'Concurrency fixture, refresh count=1, retry trace.', 'Refresh token values are never logged.', 'sk-api-security-pro -> sk-verify-pro'),
        ('Cache invalidation', 'A successful write invalidates only affected keys and refetches the canonical record.', 'Cache key trace, before/after data assertion.', 'Broad cache clears require measured justification.', 'sk-review -> sk-verify-pro'),
        ('Environment leakage', 'Development endpoints and test credentials are absent from production bundle/config.', 'Build-time config scan and bundle assertion.', 'A local green test cannot prove production secrecy.', 'sk-security-review -> sk-verify-pro'),
    ]),
    'sk-expo-native-ui': ('references/native-ui-validation-matrix.md', 'Expo native UI and platform verification matrix', [
        ('iOS/Android parity', 'The same action has equivalent semantics on iOS and Android with platform-specific affordances documented.', 'Device/simulator screenshots plus interaction assertions.', 'Web parity is checked separately.', 'sk-tester -> sk-verify-pro'),
        ('Web behavior', 'Web keyboard and pointer interaction reaches the same accessible state without native-only assumptions.', 'Browser test and accessibility tree snapshot.', 'Unsupported native APIs are surfaced as limitations.', 'sk-review -> sk-verify-pro'),
        ('Safe area', 'Content and primary controls remain inside insets across notch and gesture-navigation devices.', 'Screenshots at representative inset profiles and bounds assertion.', 'Do not validate only on a flat simulator.', 'sk-tester -> sk-verify-pro'),
        ('Dynamic type', 'Large text settings preserve readable hierarchy without clipping or hidden actions.', 'Large-font screenshots and text measurement assertions.', 'Unverified locales remain a limitation.', 'sk-a11y-design-pro -> sk-verify-pro'),
        ('Labels/focus', 'Every actionable control has an accessible label and predictable focus order.', 'Accessibility inspector output and focus traversal log.', 'Visual presence is not evidence of accessibility.', 'sk-review -> sk-verify-pro'),
        ('Dark mode', 'Contrast and semantic colors remain valid when the system theme changes.', 'Theme screenshots, contrast report, token trace.', 'Hard-coded colors block pass.', 'sk-tester -> sk-verify-pro'),
        ('Reduced motion', 'Reduced-motion preference disables nonessential animation while preserving state transitions.', 'Preference fixture and transition assertion.', 'Do not remove essential progress feedback.', 'sk-verify-pro'),
        ('Keyboard/touch target', 'Keyboard does not cover focused inputs and touch targets meet the product minimum.', 'Keyboard screenshots, hit-area measurements and device matrix.', 'Small-target exceptions require explicit product decision.', 'sk-review -> sk-verify-pro'),
    ]),
    'sk-financial-analysis-pro': ('references/financial-model-validation.md', 'Financial model validation matrix', [
        ('DCF', 'A known-answer DCF with explicit forecast, terminal value and discount-rate inputs reproduces the control valuation.', 'Model output, formula trace, control total.', 'Unsupported terminal assumptions remain disclosed.', 'sk-review -> sk-verify-pro'),
        ('Comps', 'Comparable-company multiples use a dated, labeled peer set and consistent numerator/denominator.', 'Peer list, source timestamps, normalized multiple table.', 'Do not mix LTM and NTM without labeling.', 'sk-review -> sk-verify-pro'),
        ('Assumptions', 'Every material assumption has owner, source, date, unit and rationale.', 'Assumption register and change log.', 'Unowned assumptions block decision use.', 'sk-planning -> sk-verify-pro'),
        ('Sensitivity', 'Changing WACC and terminal growth updates the valuation table monotonically within bounds.', 'Sensitivity grid and monotonicity check.', 'Nonlinear behavior is investigated, not averaged away.', 'sk-tester -> sk-verify-pro'),
        ('Units', 'Currency, scale, percentages and per-share units remain consistent across tabs and outputs.', 'Unit metadata and dimensional checks.', 'Mixed thousands/millions blocks pass.', 'sk-review -> sk-verify-pro'),
        ('Periods', 'Historical, forecast and stub periods have explicit dates and no double-counted partial year.', 'Period map and row-level date checks.', 'Missing fiscal calendar is a limitation.', 'sk-financial-analysis-pro -> sk-planning'),
        ('Known answer', 'The fixture model matches published control outputs within declared tolerance.', 'Control workbook/output and tolerance report.', 'Tolerance must be stated before comparison.', 'sk-tester -> sk-verify-pro'),
        ('Failure/rollback', 'If a source refresh changes a key assumption, preserve the prior version and require review before republishing.', 'Version diff, rollback pointer, review decision.', 'Do not overwrite the last approved model.', 'sk-review -> sk-verify-pro'),
    ]),
    'sk-fintech-integration-pro': ('references/fintech-integration-validation.md', 'Fintech integration validation matrix', [
        ('Idempotency', 'A repeated payment request with the same key creates one business effect and one ledger reference.', 'Replay trace, idempotency record, reconciliation result.', 'Key reuse across different payloads blocks processing.', 'sk-tester -> sk-verify-pro'),
        ('Webhook signature', 'Valid signatures are accepted; invalid, missing and stale signatures are rejected before mutation.', 'Signed fixtures, verification result, no-mutation assertion.', 'Never use production secrets in fixtures.', 'sk-api-security-pro -> sk-verify-pro'),
        ('Webhook replay', 'A delivered event ID is acknowledged safely on replay without duplicate fulfillment.', 'Event ledger and replay response trace.', 'Retention window must be explicit.', 'sk-review -> sk-verify-pro'),
        ('Timeout/retry', 'Bounded retries use backoff and preserve the same idempotency key.', 'Retry schedule, attempt count, final state.', 'Do not retry unknown side effects blindly.', 'sk-tester -> sk-verify-pro'),
        ('Refund/chargeback', 'Refund and chargeback states are modeled separately and reconcile to the processor report.', 'State transition log and reconciliation fixture.', 'Manual exception owner is named.', 'sk-fintech-integration-pro -> sk-review'),
        ('Rate limits', 'Provider throttling produces bounded backoff and customer-safe status without request storms.', '429 fixture, rate-limit headers, metrics trace.', 'Backoff exhaustion is an explicit failure.', 'sk-tester -> sk-verify-pro'),
        ('Token leakage', 'Logs, errors and analytics contain redacted tokens, PAN and PII.', 'Redaction test output and log scan.', 'Synthetic values only; no real payment data.', 'sk-security-review -> sk-verify-pro'),
        ('Reconciliation', 'Internal transactions, provider events and settlement totals agree or produce a named exception.', 'Three-way reconciliation report and exception queue.', 'Unresolved variance blocks final claim.', 'sk-review -> sk-verify-pro'),
    ]),
    'sk-github-actions-templates': ('references/workflow-validation-matrix.md', 'GitHub Actions workflow validation matrix', [
        ('YAML parse', 'Workflow parses and resolves referenced actions/jobs before execution.', 'Parser output and workflow-lint result.', 'Generated YAML is inspected, not trusted.', 'sk-tester -> sk-verify-pro'),
        ('Least privilege', 'Each job receives only required permissions; write access is justified.', 'Permission diff and review finding.', 'Broad write-all blocks pass.', 'sk-review-pr -> sk-verify-pro'),
        ('Fork secrets', 'Untrusted fork workflows cannot access protected secrets or publish artifacts.', 'Fork-event fixture and secret-availability assertion.', 'Never test with real secrets.', 'sk-security-review -> sk-verify-pro'),
        ('Concurrency', 'Superseded runs are canceled only where safe; release jobs are serialized.', 'Concurrency trace and cancellation policy.', 'Cancellation of migrations requires rollback plan.', 'sk-review -> sk-verify-pro'),
        ('Matrix failure', 'A failed matrix leg blocks promotion and reports the exact axis/value.', 'Matrix run log and required-check result.', 'Allow-failure must be explicit.', 'sk-tester -> sk-verify-pro'),
        ('Artifact retention', 'Artifacts retain logs/results for the declared investigation window without sensitive files.', 'Retention config and artifact inventory.', 'Retention policy is not evidence of secrecy.', 'sk-review -> sk-verify-pro'),
        ('Pinning/approval', 'Third-party actions are pinned and protected environments require approval.', 'Action reference scan and environment policy output.', 'Floating tags block release evidence.', 'sk-security-review -> sk-verify-pro'),
        ('Rollback', 'A failed deployment exposes a tested rollback path and preserves the previous artifact.', 'Rollback run, artifact IDs, post-rollback health check.', 'No rollback evidence means defer.', 'sk-deployment-pro -> sk-verify-pro'),
    ]),
    'sk-hybrid-cloud-networking': ('references/hybrid-network-troubleshooting-and-rollback.md', 'Hybrid cloud troubleshooting and rollback matrix', [
        ('BGP convergence', 'A peer loss reconverges within the declared SLO and selects the intended route.', 'Routing table snapshots, timers and convergence duration.', 'Provider timing variance is recorded.', 'sk-tester -> sk-verify-pro'),
        ('Dual-tunnel failover', 'One tunnel failure shifts traffic to the healthy tunnel without asymmetric return.', 'Tunnel state, flow trace and packet-loss window.', 'Do not call failover safe without return-path evidence.', 'sk-review -> sk-verify-pro'),
        ('Asymmetric routing', 'A captured flow shows symmetric ingress/egress or identifies the exact policy causing asymmetry.', 'Path trace and firewall counters.', 'Routing owner must approve policy changes.', 'sk-hybrid-cloud-networking -> sk-review'),
        ('MTU', 'Path MTU is measured and fragmentation/PMTUD behavior matches the service requirement.', 'Probe results at boundary sizes and interface config.', 'Application symptoms alone are insufficient.', 'sk-tester -> sk-verify-pro'),
        ('Packet loss', 'Loss is localized by hop/segment and remediation is bounded before retrying traffic.', 'Time-series metrics and packet capture metadata.', 'Do not include customer payloads in evidence.', 'sk-review -> sk-verify-pro'),
        ('DNS', 'Private/public resolution returns the intended endpoint in each environment with TTL behavior documented.', 'Resolver outputs and split-horizon matrix.', 'Stale caches are a limitation until expiry is observed.', 'sk-tester -> sk-verify-pro'),
        ('Rollback', 'A route or policy change can be reverted from a versioned config with a health check.', 'Change ID, pre-change snapshot, rollback result.', 'Emergency changes still require a follow-up owner.', 'sk-deployment-pro -> sk-verify-pro'),
        ('Limitation', 'Unknown provider-side state is marked defer with owner and exact evidence request.', 'Open-risk record and next investigation step.', 'Do not infer provider health from one probe.', 'sk-verify-pro'),
    ]),
    'sk-mlops-pro': ('references/mlops-evaluation-and-release-matrix.md', 'MLOps evaluation and release matrix', [
        ('Reproducibility', 'The same code, data snapshot and config reproduce the control metric within tolerance.', 'Run manifest, hashes and metric comparison.', 'Unpinned data or dependency is a limitation.', 'sk-tester -> sk-verify-pro'),
        ('Schema drift', 'Incoming schema changes are detected before serving and routed to a quarantine path.', 'Schema diff, alert and quarantine count.', 'Backward-compatible additions still require owner review.', 'sk-data-engineering-pro -> sk-verify-pro'),
        ('Data drift', 'A declared drift threshold triggers investigation without automatic promotion.', 'Drift report, threshold config and decision.', 'Drift is a signal, not proof of model failure.', 'sk-review -> sk-verify-pro'),
        ('Model regression', 'Candidate meets quality and slice-level guardrails against the frozen baseline.', 'Evaluation report and slice breakdown.', 'Aggregate improvement cannot mask a critical slice regression.', 'sk-tester -> sk-verify-pro'),
        ('Canary rollback', 'A canary breach stops promotion and restores the prior model/version.', 'Canary metrics, rollback event and health check.', 'Rollback owner and trigger must be named.', 'sk-deployment-pro -> sk-verify-pro'),
        ('Feature freshness', 'Feature age stays within SLA; stale features fail safe or are marked unavailable.', 'Freshness metrics and serving behavior.', 'Imputation policy must be explicit.', 'sk-data-engineering-pro -> sk-review'),
        ('Serving SLO', 'Latency/error/throughput targets are measured under representative load.', 'Load report, percentile metrics and error budget.', 'Synthetic load does not prove peak production capacity.', 'sk-performance-tuning-pro -> sk-verify-pro'),
        ('Alert thresholds', 'Alerts have threshold, owner, runbook and suppression policy; test firing is recorded.', 'Alert test event and runbook link.', 'Unowned alerts block release.', 'sk-review -> sk-verify-pro'),
    ]),
    'sk-solidity-security': ('references/solidity-attack-and-invariant-matrix.md', 'Solidity attack and invariant matrix', [
        ('Reentrancy', 'A malicious callback cannot drain funds or violate accounting during an external call.', 'Adversarial test trace and invariant result.', 'A passing unit test without adversarial path is insufficient.', 'sk-tester -> sk-verify-pro'),
        ('Access control', 'Unauthorized caller cannot invoke privileged state transitions; role changes are auditable.', 'Caller matrix, revert trace and event log.', 'Default admin assumptions must be explicit.', 'sk-review -> sk-verify-pro'),
        ('Oracle manipulation', 'Stale/outlier oracle input is rejected or bounded before pricing-sensitive mutation.', 'Oracle fixture, freshness check and invariant output.', 'Economic assumptions require domain review.', 'sk-review -> sk-verify-pro'),
        ('Upgrade/storage collision', 'Upgrade layout preserves storage slots and rejects incompatible implementation.', 'Storage layout diff and upgrade simulation.', 'Proxy admin key handling is out of scope and handed off.', 'sk-security-review -> sk-verify-pro'),
        ('Integer/rounding', 'Boundary values and rounding direction preserve conservation and never create excess funds.', 'Fuzz/property test report and balance invariant.', 'Unchecked casts block pass.', 'sk-tester -> sk-verify-pro'),
        ('Signature replay', 'A signature cannot be reused across chain, contract, nonce or deadline domains.', 'Domain-separator fixture and replay rejection trace.', 'Private keys remain synthetic.', 'sk-api-security-pro -> sk-verify-pro'),
        ('Pause/emergency', 'Pause blocks defined risky operations while preserving documented recovery and withdrawal paths.', 'State-machine test and emergency runbook check.', 'Pause authority and unpause owner are named.', 'sk-review -> sk-verify-pro'),
        ('Failure/limitation', 'Any unmodeled economic or governance assumption is recorded as defer with owner.', 'Assumption register and residual-risk decision.', 'Do not claim formal assurance from heuristic tests.', 'sk-verify-pro'),
    ]),
}

P2 = {
    'sk-spring-boot-pro': ('Spring Boot REST/service scenario evidence', 'Create an order endpoint with validation, transaction boundary and repository query budget.', 'Reject malformed input and roll back when payment persistence fails.', 'HTTP contract tests, transaction log, query-count assertion and rollback result.'),
    'sk-django-pro': ('Django REST/service scenario evidence', 'Create a DRF endpoint with serializer validation and select_related query budget.', 'Reject CSRF/permission failure and roll back a migration or transaction error.', 'API tests, permission matrix, migration status and query-count output.'),
    'sk-biz-model': ('Business model scenario evidence', 'Model a subscription workflow with actors, revenue assumptions and measurable decision criteria.', 'Mark an unowned assumption or conflicting stakeholder constraint as open rather than inventing a decision.', 'MODEL artifact, assumption register, decision log and open-question handoff.'),
    'sk-engineering-management-pro': ('Engineering management scenario evidence', 'Plan a reliability initiative with milestones, owners, risk budget and review checkpoints.', 'When capacity or evidence is missing, defer the commitment and record the decision owner.', 'Plan, dependency map, risk register and decision record.'),
    'sk-fullstack-rag-pro': ('RAG scenario evidence', 'Answer from an ACL-filtered, dated corpus with citations and a groundedness check.', 'Refuse or qualify when the corpus is stale, conflicting or does not contain the answer.', 'Retrieval trace, citation map, ACL assertion and abstention result.'),
    'sk-ai-agents-pro': ('AI agent scenario evidence', 'Execute a read-only tool workflow with bounded retries, state checkpoints and budget limits.', 'Stop on prompt injection, unauthorized side effect or repeated tool failure and hand off.', 'Tool trace, policy decision, retry count, checkpoint and next owner.'),
    'sk-ai-red-teaming-pro': ('AI red-team scenario evidence', 'Run a prompt-injection fixture and confirm the agent preserves system constraints.', 'Attempt exfiltration/tool misuse and expect refusal without leaking hidden context.', 'Fixture ID, model/version, response classification and regression record.'),
    'sk-data-science-pro': ('Data science scenario evidence', 'Evaluate a classifier with a frozen split, leakage check and slice metrics.', 'Detect leakage, missingness or multiple-comparison inflation and block the claim.', 'Data snapshot, analysis notebook/report, metric table and limitation.'),
    'sk-data-engineering-pro': ('Data engineering scenario evidence', 'Backfill an idempotent partition with schema and lineage checks.', 'Quarantine late/invalid events and recover without duplicate outputs.', 'Run manifest, row counts, schema diff, lineage and replay result.'),
    'sk-machine-learning-pro': ('Machine learning scenario evidence', 'Train against a baseline with reproducible split, robustness and fairness checks.', 'Block promotion for split contamination, regression or export/runtime incompatibility.', 'Config/data hashes, evaluation report, slice metrics and export test.'),
    'sk-office-common': ('Office artifact scenario evidence', 'Inspect and round-trip a document while preserving shared metadata and accessibility conventions.', 'Flag unsupported content or metadata loss instead of claiming fidelity.', 'Input/output paths, metadata diff, inspection log and limitation.'),
    'sk-pdf': ('PDF golden-output evidence', 'Render a representative PDF and assert page count, text presence, metadata and visual bounds.', 'Detect clipped content, missing fonts or failed round-trip extraction and block delivery.', 'Rendered page images, text extraction, metadata diff and coverage record.'),
    'sk-pptx': ('PPTX golden-output evidence', 'Render a representative deck and assert slide order, layout bounds, notes/metadata and accessibility text.', 'Detect overflow, missing assets or unsupported features and defer publication.', 'Render screenshots, object bounds, content checklist and coverage.json.'),
    'sk-xlsx': ('XLSX golden-output evidence', 'Reopen a workbook and assert sheet names, formulas, styles and known totals.', 'Detect formula loss, broken references or unsupported OOXML and block publish.', 'Round-trip report, formula scan, known-answer totals and coverage.json.'),
    'sk-docx': ('DOCX golden-output evidence', 'Round-trip a document and assert headings, tables, pagination and metadata.', 'Detect pagination drift, missing media or unsupported fields and record limitation.', 'Rendered pages, structure diff, metadata check and coverage.json.'),
    'sk-clean-architecture': ('Clean architecture scenario evidence', 'Approve a dependency map where domain rules remain independent of adapters.', 'Reject a dependency that points inward across the forbidden boundary.', 'Architecture decision, import/dependency check and rejected-coupling record.'),
    'sk-debugging-strategies': ('Debugging scenario evidence', 'Reduce a flaky timeout to a minimal reproduction and identify the causal boundary.', 'If reproduction is unavailable, record competing hypotheses and defer a fix claim.', 'Timeline, reproduction, evidence log, root-cause confidence and next action.'),
    'sk-javascript-testing-patterns': ('JavaScript testing scenario evidence', 'Test an async UI behavior with isolated fixtures, deterministic timers and accessible selectors.', 'Expose race, leaked state or flaky retry behavior and block release evidence.', 'Test output, isolation proof, selector rationale and flake result.'),
    'sk-microservices-patterns': ('Microservices scenario evidence', 'Trace a bounded request across services with deadlines, idempotency and an explicit consistency choice.', 'Reject unbounded retries or an event handler that duplicates side effects.', 'Trace, contract test, retry budget and failure/recovery decision.'),
    'sk-stride-analysis-patterns': ('STRIDE scenario evidence', 'Map a data-flow diagram to spoofing/tampering/repudiation/information-disclosure/DoS/elevation threats.', 'Record an unmitigated high-severity threat as a blocker, not a checklist pass.', 'Threat matrix, mitigation owner, residual risk and review handoff.'),
}

def row_table(rows):
    out = ['| Scenario | Expected result | Evidence | Failure/limitation | Next owner |', '|---|---|---|---|---|']
    out += [f'| {a} | {b} | {c} | {d} | {e} |' for a,b,c,d,e in rows]
    return '\n'.join(out)

for skill, (rel, title, rows) in P1.items():
    path = ROOT/'skills'/skill/rel
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''# {title}\n\nUse this matrix after the compact workflow when the task involves a high-risk claim. Fixtures must use synthetic identifiers and redacted values. The domain skill produces evidence; `sk-tester` executes tests, `sk-review`/`sk-review-pr` records findings, and `sk-verify-pro` owns the final `pass`/`block`/`defer` decision.\n\n{row_table(rows)}\n\n## Verification response shape\n\nReturn exactly:\n\n- **Claim:** the bounded domain claim being assessed.\n- **Criteria:** scenario rows and acceptance thresholds.\n- **Evidence:** paths, commands, fixture IDs, timestamps and reviewer findings.\n- **Limitations:** untested environments, assumptions, stale inputs or residual risk.\n- **Next owner:** `sk-tester`, `sk-review`, `sk-review-pr`, the named domain owner, or `sk-verify-pro`.\n\nDo not claim final release status from this matrix; hand the packet to `sk-verify-pro`.\n'''
    path.write_text(text)
    skill_path = ROOT/'skills'/skill/'SKILL.md'
    skill_text = skill_path.read_text()
    marker = f'\n## Wave 2 validation\n\nRead [`{rel}`](./{rel}) when the task requires scenario-level evidence, failure/recovery coverage, or a final verification handoff. The domain skill prepares the claim and evidence packet; `sk-verify-pro` decides `pass`, `block`, or `defer`.\n'
    if '## Wave 2 validation' not in skill_text:
        skill_path.write_text(skill_text.rstrip()+marker+'\n')

for skill, (title, positive, negative, evidence) in P2.items():
    path = ROOT/'skills'/skill/'references'/'worked-scenarios-and-evidence.md'
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''# {title}\n\nUse these scenarios as a compact fixture contract. Keep inputs synthetic and record assumptions before execution.\n\n## Positive scenario\n\n**Setup:** {positive}\n\n**Expected evidence:** {evidence}\n\n**Decision:** the scenario may be marked covered only when the evidence maps to the claim and limitations are recorded.\n\n## Negative or edge scenario\n\n**Setup:** {negative}\n\n**Expected result:** the workflow must fail safe, block, abstain, roll back, or defer; it must not silently convert missing evidence into success.\n\n**Handoff:** `sk-tester` produces execution evidence; `sk-review` or `sk-review-pr` records findings; `sk-verify-pro` owns the final `pass`/`block`/`defer` decision.\n\n## Evidence packet\n\n- **Claim:** one bounded outcome.\n- **Criteria:** positive and negative assertions above.\n- **Evidence:** fixture/output paths, command result, timestamp and reviewer findings.\n- **Limitations:** environment, unsupported features, uncertainty and residual risk.\n- **Next owner:** named specialist or `sk-verify-pro`.\n'''
    path.write_text(text)
    skill_path = ROOT/'skills'/skill/'SKILL.md'
    skill_text = skill_path.read_text()
    marker = '\n## Worked scenarios and evidence\n\nRead [`references/worked-scenarios-and-evidence.md`](./references/worked-scenarios-and-evidence.md) for one positive and one negative/edge fixture with expected output-level evidence and canonical handoff.\n'
    if '## Worked scenarios and evidence' not in skill_text:
        skill_path.write_text(skill_text.rstrip()+marker+'\n')

fixtures = ROOT/'tools'/'skill-validation'/'wave2-routing-fixtures.md'
fixtures.write_text('''# Wave 2 routing fixtures\n\nEach prompt has one primary owner. If intent is materially ambiguous, ask one clarification instead of invoking two owners for the same claim.\n\n| Prompt class | Expected primary owner | Forbidden ambiguity |\n|---|---|---|\n| accounting close/reconciliation | `sk-accounting-pro` | generic finance prose |\n| payment webhook/idempotency | `sk-fintech-integration-pro` | API design as business integration owner |\n| Expo cache/cancellation | `sk-expo-data-fetching` | native UI/testing |\n| native safe-area/accessibility | `sk-expo-native-ui` | data-fetching |\n| GitHub workflow permissions/rollback | `sk-github-actions-templates` | generic CI prose |\n| model drift/canary | `sk-mlops-pro` | generic ML only |\n| reentrancy/storage collision | `sk-solidity-security` | generic security only |\n| schema migration/restore | `sk-database-migration` | application framework |\n| final claim evidence | `sk-verify-pro` | parallel `sk-verification` invocation |\n''')

print(f'P1 packs: {len(P1)}; P2 scenario packs: {len(P2)}; routing fixture: {fixtures.relative_to(ROOT)}')
